# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2021-12-16 17:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import otree.db.models
import otree_save_the_change.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demograp_group', to='otree.Session')),
            ],
            options={
                'db_table': 'demograp_group',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_gbat_arrived', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('_gbat_grouped', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('time_Demographics', otree.db.models.LongStringField(null=True)),
                ('time_CognitiveReflectionTest', otree.db.models.LongStringField(null=True)),
                ('q_country', otree.db.models.StringField(max_length=10000, null=True, verbose_name='What country are you from?')),
                ('q_major', otree.db.models.StringField(max_length=10000, null=True, verbose_name='What is your major?')),
                ('q_age', otree.db.models.PositiveIntegerField(null=True, verbose_name='What is your age?')),
                ('q_school_year', otree.db.models.StringField(choices=[('Freshman', 'Freshman'), ('Sophomore', 'Sophomore'), ('Junior', 'Junior'), ('Senior', 'Senior'), ('Postgraduate', 'Postgraduate'), ('Other', 'Other')], max_length=10000, null=True, verbose_name='What is your school year?')),
                ('q_station', otree.db.models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23)], null=True, verbose_name='What is your computer station number? (see white sticker on computer or ask experimenter)')),
                ('q_gender', otree.db.models.StringField(max_length=10000, null=True, verbose_name='What do you identify as?')),
                ('q_income', otree.db.models.PositiveIntegerField(choices=[[1, 'less than $15,000'], [2, '$15,000 - $29,999'], [3, '$30,000 - $59,999'], [4, '$60,000 - $99,999'], [5, '$100,000 - $199,999'], [6, '$200,000 or more'], [7, 'I rather not answer this question']], null=True, verbose_name='What is the approximate annual income of your family?')),
                ('q_zipcode', otree.db.models.PositiveIntegerField(null=True, verbose_name='What is the zip code where you grew up?')),
                ('q_opinion', otree.db.models.StringField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10000, null=True, verbose_name='Were the instructions provided in this experiment clear and useful?')),
                ('q_linda', otree.db.models.StringField(choices=[('Linda is a bank teller.', 'Linda is a bank teller.'), ('Linda is a bank teller and active in the feminist movement.', 'Linda is a bank teller and active in the feminist movement.')], max_length=10000, null=True, verbose_name='Linda is 31 years old, single, outspoken, and very bright. She majored in philosophy. As a student, she was deeply concerned with issues of discrimination and social justice, and also participated in anti-nuclear demonstrations.\n\n Which of the following two alternatives is more probable?')),
                ('q_monty', otree.db.models.StringField(choices=[('change the door.', 'change the door.'), ('do not change the door.', 'do not change the door.')], max_length=10000, null=True, verbose_name='Assume that a room is equipped with three doors. Behind two are goats, and behind the third is a shiny new car. You are asked to pick a door, and will win whatever is behind it. Someone who knows what is behind the doors opens one of the other two, revealing a goat and asks you if you wish to change your selection, you:')),
                ('q_how', otree.db.models.StringField(max_length=10000, null=True, verbose_name='How did you make your choices?')),
                ('q_rule', otree.db.models.StringField(max_length=10000, null=True, verbose_name='Did you have any rule you applied to your choices?')),
                ('q_number', otree.db.models.PositiveIntegerField(null=True, verbose_name='How many studies have you participated in?')),
                ('crt_bat', otree.db.models.PositiveIntegerField(null=True)),
                ('crt_widget', otree.db.models.PositiveIntegerField(null=True)),
                ('crt_lake', otree.db.models.PositiveIntegerField(null=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='demograp.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demograp_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demograp_player', to='otree.Session')),
            ],
            options={
                'db_table': 'demograp_player',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demograp_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'demograp_subsession',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.AddField(
            model_name='player',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demograp.Subsession'),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demograp.Subsession'),
        ),
    ]
